### ISSUE TITLE
Add missing outputs in KMS DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-kms-all-inclusive#446]
Add missing outputs in KMS DA: https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/main/solutions/standard/outputs.tf
- Key Protect CRN
- Others??

**Comment by shemau** [comment]
@ocofaigh is this the reference to the key_protect_id output from the root module, but not output from the solution?

key_protect_id was identified whilst implementing #441 and fixed in #456. All other outputs from the root module were output by the solution, so no others required from that perspective.

**Comment by ocofaigh** [comment]
@shemau I created the issue because I noticed the CRN of the key protect instance was not in the DA outputs. Unrelated to any other issue

**Comment by shemau** [comment]
Added PR https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/pull/555 to add missing output to called module. Once this is merged, it can be output from this module.

**Comment by shemau** [comment]
Resolved in #456 adding outputs for both `key_protect_id` and `key_protect_crn`.
